CREATE TABLE LOGQUEUE (

   EXCHANGENAME VARCHAR(255),
   MESSAGE VARCHAR(1024),
   QUEUENAME VARCHAR(255) NOT NULL,
   ROUTINGKEY VARCHAR(255),
   IDENTIFIER VARCHAR(36) NOT NULL,
   PRIMARY KEY (IDENTIFIER, QUEUENAME)
);

PARTITION TABLE LOGQUEUE ON COLUMN QUEUENAME;

CREATE PROCEDURE FROM CLASS Insert;
CREATE PROCEDURE FROM CLASS Select;



CREATE TABLE ACTIONS (

   EXCHANGENAME VARCHAR(255),
   QUEUENAME VARCHAR(255) NOT NULL,
   ROUTINGKEY VARCHAR(255),
   IDENTIFIER VARCHAR(36) NOT NULL,
   ACTIONID VARCHAR(36) NOT NULL,
   PRIMARY KEY (IDENTIFIER, QUEUENAME)
);

PARTITION TABLE ACTIONS ON COLUMN QUEUENAME;



