import org.voltdb.*;


public class UI_SelectActionsForCheckID extends VoltProcedure {

	

	public final SQLStmt sqlFindAllDetails = new SQLStmt(
			"SELECT ACTION.ACTIONID, ACTION.ACTIONNAME, ACTION.TARGETENDPOINTID, OUTBOUNDPROPERTYACTION.OUTBOUNDPROPERTYID, " +
			"OUTBOUNDPROPERTYACTION.INBOUNDPROPERTYID, OUTBOUNDPROPERTYACTION.CURRENTSTATEPROPERTYID, " +
			"OUTBOUNDPROPERTYACTION.CUSTOMPAYLOAD FROM ACTION INNER JOIN OUTBOUNDPROPERTYACTION ON " +
			"ACTION.ACTIONID = OUTBOUNDPROPERTYACTION.ACTIONID AND ACTION.CHECKID = ? ORDER BY ACTION.ACTIONID, "
			+ "ACTION.ACTIONNAME, ACTION.TARGETENDPOINTID, OUTBOUNDPROPERTYACTION.OUTBOUNDPROPERTYID, " +
			"OUTBOUNDPROPERTYACTION.INBOUNDPROPERTYID, OUTBOUNDPROPERTYACTION.CURRENTSTATEPROPERTYID, " +
			"OUTBOUNDPROPERTYACTION.CUSTOMPAYLOAD;");

	public VoltTable[] run(
			String checkpathID,
			String checkID)
			throws VoltAbortException {
		voltQueueSQL(sqlFindAllDetails, checkID);
		// voltExecuteSQL();
		return voltExecuteSQL();
	}
}